---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: {{ .Values.application.name }}-webhook-hom
spec:
  serviceAccountName: pipeline
  triggers:
    - name: {{ .Values.application.name }}-webhook-hom
      interceptors:
        - name: "add short sha"
          ref:
            name: "cel"
          params:
          - name: "overlays"
            value:
            - key: short_sha
              expression: "body.after.truncate(7)"
            - key: branch_name
              expression: "body.ref.split('/')[2]"
      bindings:
        - ref: tb-gogs-triggerbinding-hom
      template:
        ref: tt-{{ .Values.application.name }}-trigger-template-hom
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: el-{{ .Values.application.name }}-webhooks-hom
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: {{ .Values.application.name }}-webhook-hom
spec:
  port:
    targetPort: http-listener
  to:
    kind: "Service"
    name: el-{{ .Values.application.name }}-webhook-hom
    weight: 100
