---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: tb-gogs-triggerbinding-hom
spec:
  params:
  - name: ref
    value: $(body.ref)  
  - name: gitrevision
    value: $(body.after)
  - name: gitshortsha
    value: $(body.short_sha)
  - name: gitbranchname
    value: $(body.branch_name)
  - name: gitrepositoryurl
    value: $(body.repository.clone_url)
  - name: contenttype
    value: $(header.Content-Type)
