kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pipeline-build-workspace
  namespace: oqss-cicd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2
  volumeMode: Filesystem
