---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipeline-builder-image-puller-{{ .Values.application.environments.dev }}
  namespace: {{ .Values.application.environments.cicd }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.pipeline.sa.default }}
  namespace: {{ .Values.application.environments.dev }}
roleRef:
  kind: ClusterRole
  name: system:image-puller
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipeline-builder-image-puller-{{ .Values.application.environments.hom }}
  namespace: {{ .Values.application.environments.cicd }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.pipeline.sa.default }}
  namespace: {{ .Values.application.environments.hom }}
roleRef:
  kind: ClusterRole
  name: system:image-puller
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipeline-builder-image-puller-{{ .Values.application.environments.prod }}
  namespace: {{ .Values.application.environments.cicd }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.pipeline.sa.default }}
  namespace: {{ .Values.application.environments.prod }}
roleRef:
  kind: ClusterRole
  name: system:image-puller
  apiGroup: rbac.authorization.k8s.io